/*======================================
	Loadout for Jet Pilots (nato)
======================================*/
params ["_linkItems", "_weapons", "_magazine", "_scopes", "_uniforms", "_vests", "_headgears", "_backpacks", "_goggle"];

[
  [],
  [],
  [
    "hgun_P07_F",
    "",
    "",
    "",
    ["16Rnd_9x21_Mag",16],
    [],
    ""
  ],
  [
    "U_B_PilotCoveralls",
    []
  ],
  [
    "V_Rangemaster_belt",
    [
      ["ACE_IR_Strobe_Item",1],
      ["ACE_microDAGR",1],
      ["16Rnd_9x21_Mag",3,16],
      ["SmokeShellRed",1,1],
      ["SmokeShellGreen",1,1],
      ["ACE_Chemlight_HiGreen",1,1],
      ["ACE_Chemlight_HiRed",1,1]
    ]
  ],
  [],
  "RHS_jetpilot_usaf",
  "rhsusf_oakley_goggles_clr",
  [],
  _linkItems
]