PREP(acreInit);
PREP(acreOfficerGod);
PREP(acreSetDefaultChannel);
PREP(radioJammerInit);
PREPMAIN(radioJammer);
PREP(spectrumDeviceInit);
PREP(spectrumDeviceOverride);
PREP(spectrumDevice);
PREP(initPropRadios);