/*======================================
	Loadout for Medics (usMC)
======================================*/
params ["_linkItems", "_uniform", "_headgear", "_goggle"];

[
  [
    "rhs_weap_m16a4_carryhandle",
    "",
    "rhsusf_acc_anpeq15_bk",
    "rhsusf_acc_compm4",
    ["rhs_mag_30Rnd_556x45_M855_Stanag",30],
    [],
    ""
  ],
  [],
  [],
  [
    _uniform,
    []
  ],
  [
    "rhsusf_spc_corpsman",
    [
      ["rhs_mag_30Rnd_556x45_M855_Stanag",8,30],
      ["rhs_mag_m18_red",1,1]
    ]
  ],
  [
    "rhsusf_assault_eagleaiii_coy_medic",
    [
		["ACE_elasticBandage",32],
		["ACE_packingBandage",32],
		["ACE_bloodIV_250",8],
		["ACE_bloodIV_500",4],
		["ACE_bloodIV",4],
		["ACE_surgicalKit",1],
		["ACE_personalAidKit",2],
		["ACE_splint",10],
		["ACE_morphine",12],
		["ACE_epinephrine",12],
		["ACE_EarPlugs",1]
    ]
  ],
  _headgear select 1,
  "rhsusf_oakley_goggles_clr",
  [],
  _linkItems
]