class Loadouts
{
	#include "bafNewTemplate\loadouts.hpp"
	#include "bokoHaram\loadouts.hpp"
	#include "macv\loadouts.hpp"
	#include "macvNewTemplate\loadouts.hpp"
	#include "pmc\loadouts.hpp"
	#include "russian\loadouts.hpp"
	#include "serbian\loadouts.hpp"
	#include "serbianNewTemplate\loadouts.hpp"
	#include "spetznaz\loadouts.hpp"
	#include "taliban\loadouts.hpp"
	#include "usArmy\loadouts.hpp"
	#include "usArmyNewTemplate\loadouts.hpp"
	#include "usArmySF\loadouts.hpp"
	#include "usArmySFNewTemplate\loadouts.hpp"
    #include "usMC\loadouts.hpp"
	#include "usMCNewTemplate\loadouts.hpp"
    #include "usKorea\loadouts.hpp"
};