class Loadouts
{
	#include "baf\loadouts.hpp"
	#include "bafCW\loadouts.hpp"
	#include "cbrn\loadouts.hpp"
	#include "customSwat\loadouts.hpp"
	#include "gendarmerieSwat\loadouts.hpp"
	#include "macv\loadouts.hpp"
	#include "pmc\loadouts.hpp"
	#include "russian\loadouts.hpp"
	#include "serbian\loadouts.hpp"
	#include "snowTigers\loadouts.hpp"
	#include "spetznaz\loadouts.hpp"
	#include "taliban\loadouts.hpp"
	#include "usArmy\loadouts.hpp"
	#include "usArmySF\loadouts.hpp"
    #include "usKorea\loadouts.hpp"
	#include "usMC\loadouts.hpp"
	#include "vnSwat\loadouts.hpp"
};