/*======================================
	Loadout for Jet Pilots (serbian)
======================================*/
params ["_linkItems", "_uniform", "_vests", "_headgear", "_backpacks"];

[
  [],
  [],
  [
    "rhsusf_weap_glock17g4",
    "",
    "",
    "",
    ["rhsusf_mag_17Rnd_9x19_JHP",15],
    [],
    ""
  ],
  [
    "U_B_PilotCoveralls",
    []
  ],
  [
    "V_Rangemaster_belt",
    [
      ["ACE_IR_Strobe_Item",1],
      ["ACE_microDAGR",1],
      ["rhsusf_mag_17Rnd_9x19_JHP",3,15],
      ["SmokeShellRed",1,1],
      ["SmokeShellGreen",1,1],
      ["ACE_Chemlight_HiGreen",1,1],
      ["ACE_Chemlight_HiRed",1,1]
    ]
  ],
  [],
  "RHS_jetpilot_usaf",
  "rhsusf_oakley_goggles_clr",
  [],
  _linkItems
]